apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  selector:
    matchLabels:
      app: wordpress-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      nodeSelector:
          task: worker1
      containers:
      - image: wordpress
        name: wordpress-cont
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-svc
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        ports:
        - containerPort: 80
          name: wordpress-cont
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        hostPath:
          path: /home/seng/wordpress-data
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  ports:
    - port: 80
      # targetPort: 80
        # protocol: TCP
  selector:
    app: wordpress-app
  type: NodePort